### PR TITLE
51 documentation updates v01

### PR DESCRIPTION
**Pull request by edgar-manukyan**
Thank you for your Pull Request! We have developed this task checklist from the
[Development Process
Guide](https://pharmaverse.github.io/sdtm.oak/CONTRIBUTING.html)
to help with the final steps of the process. Completing the below tasks helps to
ensure our reviewers can maximize their time on your code as well as making sure
the oak codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task
or check off that it is not relevant to your Pull Request. This checklist is
part of the Github Action workflows and the Pull Request will not be merged into
the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull z
Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the 
[tidyverse style guide](https://style.tidyverse.org/). Run 
`styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should
consider realistic data scenarios and edge cases, e.g. empty datasets, errors,
boundary cases etc. - See 
[Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you 
fully follow the 
[deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples, including keywords
and families. Refer to the 
[categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the
`NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it
has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build oak site `pkgdown::build_site()` and check that all affected
examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by rammprasad** [comment]
@edgar-manukyan @galachad @ramiromagno - I think all checks passed in the pipeline. But it is not showing up. Can you help me resolve this? From a content perspective, everything is complete.

**Comment by ramiromagno** [comment]
The `DT` package is in Suggests but should be in Imports because it's used in `dataset_oak_vignette()`.

**Comment by ramiromagno** [comment]
Also, with R version 4.4 and more recent packages, I am also getting:

```
Using an external vector in selections was deprecated in tidyselect 1.1.0.
i Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(.after)

  # Now:
  data %>% select(all_of(.after))
```

These warnings come from the functions implemented in the branch with conditioned data frames, and I know I have fixed them before we merged into main. So I guess this branch does not yet have the most up-to-date version of main integrated into it...?

**Comment by rammprasad** [comment]
I have merged the latest main to this branch. Not sure what is going on. It doesn't show any differences.

**Review by ramiromagno — APPROVED** [review]
@rammprasad All good. I just added one commit to update the WORDLIST.

**Review by ramiromagno — APPROVED** [review]
All good.

**Review by rammprasad — APPROVED** [review]

**Pull request merged**
