### PR TITLE
Add test case for `baseline_timepoints` in `derive_blfl` function

### PR DESCRIPTION
**Pull request by ShiyuC**
This PR touches https://github.com/pharmaverse/sdtm.oak/issues/59, bullet point 3. 

- Modify the test case to cover the usage of `baseline_timepoints`.
- Add different examples for the function

Please check off each taskbox as an acknowledgment that you completed the task
or check off that it is not relevant to your Pull Request. This checklist is
part of the Github Action workflows and the Pull Request will not be merged into
the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull z
Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the 
[tidyverse style guide](https://style.tidyverse.org/). Run 
`styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should
consider realistic data scenarios and edge cases, e.g. empty datasets, errors,
boundary cases etc. - See 
[Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you 
fully follow the 
[deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords
and families. Refer to the 
[categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the
`NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it
has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build oak site `pkgdown::build_site()` and check that all affected
examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by ShiyuC** [comment]
@edgar-manukyan @ramiromagno May I request your review of this small MR? Thanks in advance

**Review by ramiromagno — COMMENTED** [review]
Hi @ShiyuC:

When it comes to this PR specifically, I think that the changes are working as expected.

I took a look at the function code itself and there are a few things I personally think should be improved (but this might be addressed on a separate issue or not... I leave it up to you, Edgar and Ramm to decide)

- ISO 8601 formatted dates are being used as character and not as date-times on their own right. This means that date and time comparisons are being done lexicographically, which I find dangerous (even though I understand the measures taken at `dtc_datepart()` and `dtc_timepart()` to make sure the format is comparable).  
- Using dplyr verbs (`dplyr::mutate()`, `dplyr::na_if()`, `tidyr::drop_na()`) to make code more readable here:
  ```r
    bad_orres_rows <- is.na(ds_mod[[domain_prefixed_names["orres"]]]) |
    trimws(ds_mod[[domain_prefixed_names["orres"]]]) %in% c("ND", "NOT DONE", "")
    ds_mod <- ds_mod[!bad_orres_rows, ]
  ```
- I think there is a bug in line 355, `var_tpt` -> `tpt`
  ```r
  con_col <- c(domain_prefixed_names[c("testcd", "dtc", "var_tpt")], "VISIT")
  ```
- Not that I think it makes a difference in the resulting computations, but it would be more human-readable, I would change `sdtm_in` to `ds_mod`:
  ``` r
     con_col <- con_col[con_col %in% names(sdtm_in)]
  ```
- Is the setting of `<unspecified>` something that is part of the SDTM standard?
- Replace `rbind()` with dplyr's equivalent
- Replace `dplyr::arrange_at()` with `arrange()` as the former is superseded.
- Replace the pattern `get(domain_prefixed_names["tpt"])` by idiomatic rlang alternatives, e.g. `!!rlang::sym(...)` or `{{...}}`.

**Comment by edgar-manukyan** [comment]
Thanks team. Shall we add a new issue with Ramiro's nice findings/suggestions and refactor the derive_blfl in that issue?

**Review by edgar-manukyan — APPROVED** [review]

**Comment by ShiyuC** [comment]
> Hi @ShiyuC:
> 
> When it comes to this PR specifically, I think that the changes are working as expected.
> 
> I took a look at the function code itself and there are a few things I personally think should be improved (but this might be addressed on a separate issue or not... I leave it up to you, Edgar and Ramm to decide)
> 
> * ISO 8601 formatted dates are being used as character and not as date-times on their own right. This means that date and time comparisons are being done lexicographically, which I find dangerous (even though I understand the measures taken at `dtc_datepart()` and `dtc_timepart()` to make sure the format is comparable).
> * Using dplyr verbs (`dplyr::mutate()`, `dplyr::na_if()`, `tidyr::drop_na()`) to make code more readable here:
>   ```r
>     bad_orres_rows <- is.na(ds_mod[[domain_prefixed_names["orres"]]]) |
>     trimws(ds_mod[[domain_prefixed_names["orres"]]]) %in% c("ND", "NOT DONE", "")
>     ds_mod <- ds_mod[!bad_orres_rows, ]
>   ```
> * I think there is a bug in line 355, `var_tpt` -> `tpt`
>   ```r
>   con_col <- c(domain_prefixed_names[c("testcd", "dtc", "var_tpt")], "VISIT")
>   ```
> * Not that I think it makes a difference in the resulting computations, but it would be more human-readable, I would change `sdtm_in` to `ds_mod`:
>   ```r
>      con_col <- con_col[con_col %in% names(sdtm_in)]
>   ```
> * Is the setting of `<unspecified>` something that is part of the SDTM standard?
> * Replace `rbind()` with dplyr's equivalent
> * Replace `dplyr::arrange_at()` with `arrange()` as the former is superseded.
> * Replace the pattern `get(domain_prefixed_names["tpt"])` by idiomatic rlang alternatives, e.g. `!!rlang::sym(...)` or `{{...}}`.

We can probably add these comments to issue #59

**Comment by ShiyuC** [comment]
- ISO 8601 formatted dates are being used as character and not as date-times on their own right. This means that date and time comparisons are being done lexicographically, which I find dangerous (even though I understand the measures taken at dtc_datepart() and dtc_timepart() to make sure the format is comparable).
**_Confirmed that ISO 8601 will be applied to date time variables before blfl derivation, so comparing in lexicographic order should be fine. I will add code in there to check the format and give message_**
- Is the setting of <unspecified> something that is part of the SDTM standard?
**_This is not SDTM standard, but we fill in the value to make sure VISIT does not have blank values._**

**Pull request merged**
